# Generated by Django 5.2.14 on 2026-07-13 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='creared_date',
            new_name='created_date',
        ),
    ]
